### ISSUE TITLE
Package Rewrite

### ISSUE THREAD

**Issue by akaszynski** [Marcello-Sega/pytetgen#2]
Hello,

I've also generated a pytetgen module, but it's quite a bit more complete than this module and includes several extra features including mesh repair using pymeshfix and plotting using vtkInterface.  I was wondering how to proceed.  It would be quite pull to submit.

**Comment by Marcello-Sega** [comment]
Hi, 
thanks for writing me. Can I have a look at it? I can't see it in your repos.

**Comment by akaszynski** [comment]
I've yet to upload it.  I'll upload it by early next week.

**Comment by thomasaarholt** [comment]
@akaszynski did you ever upload this?

**Comment by akaszynski** [comment]
> @akaszynski did you ever upload this?

A few years ago :)

https://github.com/pyvista/tetgen
