### ISSUE TITLE
make cylinder mesh

### ISSUE THREAD

**Issue by BENYSU** [Marcello-Sega/pytetgen#8]
Dear 
I try make cylinder mesh by 

import pyvista as pv
import tetgen
import numpy as np
pv.set_plot_theme('document')
cylinder=pv.cylinder()
tet = tetgen.TetGen(cylinder)

But it remind 'AttributeError: module 'pyvista' has no attribute 'cylinder''
Thank you very much!

**Comment by Marcello-Sega** [comment]
Hi,

As the error message suggests, the problem is related to pyvista, not to pytetgen.

**Comment by BENYSU** [comment]
Thank you very much for your reply and how can overcome the problem? And  do you have the example of making cylinder mesh?
Thank you very much!

**Comment by Marcello-Sega** [comment]
No, sorry, you have to ask the pyvista community in case.

**Comment by BENYSU** [comment]
Ok thank you very much
